global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using MediatR;
global using AutoMapper.QueryableExtensions;
global using VowelBonus.Shared.Common.Models;
global using VowelBonus.Shared.DTOs;
global using VowelBonus.Domain.Common;
global using VowelBonus.Domain.Entities;
global using VowelBonus.Domain.Interfaces;
